
apiVersion: apps/v1
kind: Deployment
metadata:
 name: rtty-deployment3
spec:
 replicas: 1
 selector:
   matchLabels:
     app: rtty3
 template:
   metadata:
     labels:
       app: rtty3
   spec:
     shareProcessNamespace: true
     containers:
     - name: rtty3
       image: pawwlyk52/rttyexe2
       # imagePullPolicy: Never
       ports:
       - containerPort: 9994
       env:
        - name: TERM
          value: "xterm"
        - name: PORT
          value: "9994"

---

apiVersion: v1
kind: Service
metadata:
 name: rtty-service3
 labels:
   app: rtty3
spec:
 selector:
   app: rtty3
 ports:
   - protocol: TCP
     port: 9994
     targetPort: 9994
     # nodePort: 30081
 type: NodePort

--- 

# apiVersion: v1
# kind: Service
# metadata:
#   name: rttylb
#   annotations:
# spec:
#   ports:
#   - port: 80
#     targetPort: 9994
#   selector:
#     app: rtty
#   type: LoadBalancer
