# https://kubernetes.io/docs/concepts/configuration/configmap/
apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfig
  namespace: default
data:
  testkey: "hello"
  testkey2: "hello2"
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: rtty-deployment
spec:
 replicas: 1
 selector:
   matchLabels:
     app: rtty
 template:
   metadata:
     labels:
       app: rtty
   spec:
     shareProcessNamespace: true
     enableServiceLinks: false
     containers:
     - name: rtty
       image: pawwlyk52/rttyexe_env
       # imagePullPolicy: Never
       # ports:
       # - containerPort: 9994
       env:
        - name: TERM
          value: "xterm"
        - name: PORT
          value: "9994"
       volumeMounts:
         - name: testv
           mountPath: /home/test/testconfig
           subPath: testkey
     volumes:
       - name: testv
         configMap:
           name: myconfig
           # items:
           #   - key: testkey
           #     path: myconfigmap.conf
           #   - key: testkey2
           #     path: myconfigmap2.conf
---
apiVersion: v1
kind: Service
metadata:
 name: rtty-service
 labels:
   app: rtty
spec:
 selector:
   app: rtty
 ports:
   - protocol: TCP
     port: 9994
     targetPort: 9994
     # nodePort: 30081
 type: ClusterIP

--- 

# apiVersion: v1
# kind: Service
# metadata:
#   name: rttylb
#   annotations:
# spec:
#   ports:
#   - port: 80
#     targetPort: 9994
#   selector:
#     app: rtty
#   type: LoadBalancer
