version: '3.3'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=ozon
      - POSTGRES_PASSWORD=ozon
      - POSTGRES_DB=ozon
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ozon -d ozon"]
        interval: 10s
        timeout: 5s
        retries: 5

  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ozon.ru
      PGADMIN_DEFAULT_PASSWORD: ozon
      PGADMIN_LISTEN_PORT: 8081
    ports:
      - "8081:8081"
    volumes:
      - /var/lib/pgadmin
    links:
      - "db:pgsql-server"

  migrate:
     image: migrate/migrate
     volumes:
        - ./migrations:/migrations
     command: -source=file://migrations -database postgres://ozon:ozon@pgsql-server:5432/ozon?sslmode=disable up 4
     depends_on:
       db:
         condition: service_healthy
     links: 
        - "db:pgsql-server"  

  grpc_client:
     build:
          context: .
          dockerfile: Dockerfile_client
     network_mode: "host"

  grpc_server:
      build:
          context: .
          dockerfile: Dockerfile_server
        # ports:
            # - "12201:12201"
            # - "8888:8888"
      network_mode: "host"
