project_name: rtty
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: Darwin
      linux: Linux
      386: i386
      amd64: x86_64
builds:
  - main: .
    ldflags:
      - -s -w
      - -X github.com/skanehira/rtty/cmd.Version={{.Version}}
      - -X github.com/skanehira/rtty/cmd.Revision={{.ShortCommit}}
    goos:
      - linux
      - darwin
